version: "3.8"

services:
  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - VITE_TEAM_SERVICE_URL=${VITE_TEAM_SERVICE_URL}
      - VITE_TOURNAMENT_SERVICE_URL=${VITE_TOURNAMENT_SERVICE_URL}
    depends_on:
      - team-service
      - tournament-service
    networks:
      - app-network

  # Team service
  team-service:
    build: ./backend/team-service
    ports:
      - "${TEAM_SERVICE_PORT}:8000"
    environment:
      - DB_USER=${TEAM_DB_USER}
      - DB_PASSWORD=${TEAM_DB_PASSWORD}
      - DB_NAME=${TEAM_DB_NAME}
      - TEAM_DB_HOST=${TEAM_DB_HOST}
      - DB_PORT=5432
    depends_on:
      team-db:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # Tournament service
  tournament-service:
    build: ./backend/tournament-service
    ports:
      - "${TOURNAMENT_SERVICE_PORT}:8000"
    environment:
      - DB_USER=${TOURNAMENT_DB_USER}
      - DB_PASSWORD=${TOURNAMENT_DB_PASSWORD}
      - DB_NAME=${TOURNAMENT_DB_NAME}
      - TOURNAMENT_DB_HOST=${TOURNAMENT_DB_HOST}
      - DB_PORT=5432
    depends_on:
      tournament-db:
        condition: service_healthy
      team-service:
        condition: service_started
    networks:
      - app-network
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # Team database
  team-db:
    image: postgres:15-alpine
    ports:
      - "${TEAM_DB_EXTERNAL_PORT}:5432"
    environment:
      - POSTGRES_DB=${TEAM_DB_NAME}
      - POSTGRES_USER=${TEAM_DB_USER}
      - POSTGRES_PASSWORD=${TEAM_DB_PASSWORD}
    volumes:
      - team_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEAM_DB_USER} -d ${TEAM_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Tournament database
  tournament-db:
    image: postgres:15-alpine
    ports:
      - "${TOURNAMENT_DB_EXTERNAL_PORT}:5432"
    environment:
      - POSTGRES_DB=${TOURNAMENT_DB_NAME}
      - POSTGRES_USER=${TOURNAMENT_DB_USER}
      - POSTGRES_PASSWORD=${TOURNAMENT_DB_PASSWORD}
    volumes:
      - tournament_db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TOURNAMENT_DB_USER} -d ${TOURNAMENT_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  team_db_data:
  tournament_db_data:

networks:
  app-network:
    driver: bridge
